#winner
def victory():
    print("=" * 90)
    print("🎉 YOU DID IT! 🎉".center(90))
    print()
    print(" " * 20 + "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨")
    print(" " * 18 + "✨                                     ✨")
    print(" " * 16 + "✨           █████████████████           ✨")
    print(" " * 14 + "✨        ███                   ███        ✨")
    print(" " * 12 + "✨      ███       \\  |  /        ███      ✨")
    print(" " * 10 + "✨     ██         -- 😄 --         ██     ✨")
    print(" " * 8 + "✨     ██        /  |  \\        ██     ✨")
    print(" " * 10 + "✨      ███                     ███      ✨")
    print(" " * 12 + "✨        ███       \\___/       ███        ✨")
    print(" " * 14 + "✨           █████████████████           ✨")
    print(" " * 16 + "✨                                     ✨")
    print(" " * 18 + "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨")
    print()
    print(" " * 10 + "💰💰💰💰💰   J A C K P O T   💰💰💰💰💰")
    print()
    print(" " * 5 + "╔" + "═" * 78 + "╗")
    print(" " * 5 + "║" + " " * 78 + "║")
    print(" " * 5 + "║" + "   YOU SAVED HUMANITY.   ".center(78) + "║")
    print(" " * 5 + "║" + "   YOUR NAME WILL ECHO THROUGH THE HUMANITY FOREVER.     ".center(78) + "║")
    print(" " * 5 + "║" + " " * 78 + "║")
    print(" " * 5 + "╚" + "═" * 78 + "╝")
    print()
    print()
    print("=" * 90)